### ISSUE TITLE
Ignores username when using ssh-ed25519 

### ISSUE THREAD

**Issue by lclc** [joushou/sshmuxd#13]
When I try to login with my ed25519 key I get 

> unknown user authorized

Since the key is still valid it works, but only for machines that are available for everyone.

**Comment by kennylevinsen** [comment]
ed25519 was first added to the crypto/ssh lib half a year after my last build. A simple rebuild with a more recent toolchain might fix this. The username is extracted from some key-info, so it seems like it's just ignoring your key altogether.

**Comment by lclc** [comment]
I built from source, so that should be ok.

The key works since I can login, but it can't see my user name.

> 2017/01/07 15:37:59 92.XXXXX:60270: unknown user authorized (username: ubuntu)
2017/01/07 15:37:59 92.XXXXXX:60270: unknown user connecting to 159.100.YYYYY:22

But looking at your code it seems like it might be a problem in crypto/ssh itself.

**Comment by kennylevinsen** [comment]
The "username" is simply the client-provided username. This is printed so that when no other identifying data is present, you can at least see what user was attempted used.

I have just built everything, and ed25519 works as it should, but I found a different problem around multi-key setups. The SSH client tries each key once, and doesn't move on to the next if authentication doesn't fail - but with "noauth" hosts enabled, login never fails. In my case, I also had an ecdsa key which was attempted used before my ed25519 key, leaving me logged in as "unknown" despite having the proper key available.

I'll see if there's something to make noauth hosts work in this setup, although I am not entirely sure what I'll end up doing. It should work if you avoid noauth for now.

**Comment by lclc** [comment]
You're right. No idea what was wrong with my key, but now I generated a new ed25519 and it works.

So one more question - maybe that's a general miss-understanding from me how sshmuxd is supposed to work:

Do I need to have the ssh public key (e.g. the newly generated ed25519) in each servers .ssh/authorized_keys file?  Because otherwise my login doesn't work.
I though having only the SSH pub key of the sshmuxd (the one belonging to the hostkey priv key) should be enough? Isn't that the purpose of the hostkey?

**Comment by kennylevinsen** [comment]
hostkey is part of the server's private key towards the client. All SSH servers have this, although it is often slightly hidden as openssh-server generates the key on first launch. It allows the client to guarantee that they are connected to the correct server, and not one that tries to shake sensitive information out of you. The public part of the hostkey is what goes into your known_hosts file.

sshmux forwards the user "as-is", so indeed the public key is also needed at the destination. What sshmux does is provide control of who can go where, while also being limited in functionality so that the service is hard to abuse.

sshmux could be made to use its own private key to authenticate to the backend with relatively little coding effort, but I don't think this would be a common usecase. It would also be much less safe, as compromise of the sshmux machine would lead to a private key that gives access to everything. :/

**Comment by lclc** [comment]
ah ok, thanks a lot for clarifying.

**Comment by lclc** [comment]
I'll close this since the initial issue is solved.
