### ISSUE TITLE
Password authentication

### ISSUE THREAD

**Issue by WolfeCub** [joushou/sshmuxd#20]
Is it possible to run this with password authentication rather than public key auth?

Thanks!

**Comment by kennylevinsen** [comment]
Sorry for the late reply that you probably no longer need—that's what happens when you get a notification at work and think "I'll reply to it this evening".

It only works for public key authentication. It's a bad idea to try to do this kind of thing with password authentication. It is also a bad idea to use password authentication for SSH in general.
